import React, { useCallback, useEffect, useRef, useState } from "react";
import { api } from "../services/api";

const SUGGESTIONS = [
  "Average amount of a recovered case",
  "How many cases over 5000 dollars?",
  "Which customers had the most failures?",
  "Total recovered by failure category",
  "Top 3 cases over 3000 dollars",
  "Did it beat the baseline?",
  "What did the policy engine block?",
  "Show me the dead letter queue",
];

/** Minimal inline markdown: **bold** and `code`. Deliberately not a library - the text
 *  is generated by our own engine, so the grammar it can emit is known and small. */
function render(text) {
  const out = [];
  const re = /(\*\*[^*]+\*\*|`[^`]+`)/g;
  let last = 0, m;
  while ((m = re.exec(text)) !== null) {
    if (m.index > last) out.push(text.slice(last, m.index));
    const tok = m[0];
    out.push(tok.startsWith("**")
      ? <b key={m.index}>{tok.slice(2, -2)}</b>
      : <code key={m.index} className="mono">{tok.slice(1, -1)}</code>);
    last = m.index + tok.length;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}

function Bubble({ turn, onOpenCase }) {
  if (turn.role === "user") {
    return <div className="chat-turn user"><div className="bubble">{turn.text}</div></div>;
  }
  return (
    <div className="chat-turn bot">
      <div className="bubble">
        {turn.text.split("\n").map((line, i) =>
          line.trim() === ""
            ? <div key={i} style={{ height: 6 }} />
            : <div key={i}>{render(line)}</div>)}
        {turn.caseIds?.length > 0 && (
          <div className="chat-cases">
            {turn.caseIds.slice(0, 8).map((id) => (
              <button key={id} className="act" onClick={() => onOpenCase(id)}>{id}</button>
            ))}
          </div>
        )}
        {turn.intent && (
          <div className="chat-meta">
            <div>
              resolved to <code className="mono">{turn.intent}</code>
              {" · "}<code className="mono">{turn.source}</code>
              {turn.matched != null && ` · ${turn.matched.toLocaleString()} rows matched`}
            </div>
            {turn.sql && <div className="chat-sql mono">{turn.sql}</div>}
          </div>
        )}
      </div>
    </div>
  );
}

export function Assistant({ onOpenCase }) {
  const [turns, setTurns] = useState([]);
  const [q, setQ] = useState("");
  const [busy, setBusy] = useState(false);
  const [useLLM, setUseLLM] = useState(false);
  const inputRef = useRef(null);
  const endRef = useRef(null);

  useEffect(() => { inputRef.current?.focus(); }, []);
  useEffect(() => { endRef.current?.scrollIntoView({ block: "end" }); }, [turns, busy]);

  const send = useCallback(async (question) => {
    const text = (question ?? q).trim();
    if (!text || busy) return;
    setTurns((t) => [...t, { role: "user", text }]);
    setQ("");
    setBusy(true);
    try {
      const a = await api.chat(text, useLLM ? "llm" : "keywords");
      setTurns((t) => [...t, { role: "bot", text: a.text, intent: a.intent,
                               source: a.source, caseIds: a.case_ids,
                               sql: a.sql, matched: a.data?.matched }]);
    } catch (e) {
      setTurns((t) => [...t, { role: "bot", text: `Could not answer: ${e}` }]);
    } finally {
      setBusy(false);
      inputRef.current?.focus();
    }
  }, [q, busy, useLLM]);

  return (
    <div className="card">
      <h2>Ask about this run</h2>
      <div className="sub">
        Questions are compiled into a query over the case table - filters, aggregates and
        groupings - and executed as SQL. Every figure comes from the database; nothing is
        generated. If part of a question cannot be expressed against the stored data, the
        answer says so rather than quietly answering a broader question.
      </div>

      <div className="chat-log">
        {turns.length === 0 && (
          <div className="empty" style={{ padding: "10px 0 18px" }}>
            Ask a question, or start with one of these:
          </div>
        )}
        {turns.map((t, i) => <Bubble key={i} turn={t} onOpenCase={onOpenCase} />)}
        {busy && <div className="chat-turn bot"><div className="bubble">…</div></div>}
        <div ref={endRef} />
      </div>

      {turns.length === 0 && (
        <div className="chat-suggest">
          {SUGGESTIONS.map((s) => (
            <button key={s} className="act" onClick={() => send(s)}>{s}</button>
          ))}
        </div>
      )}

      <form className="chat-input" onSubmit={(e) => { e.preventDefault(); send(); }}>
        <input ref={inputRef} type="text" value={q} placeholder="Ask about cases, revenue, rules&hellip;"
               onChange={(e) => setQ(e.target.value)} disabled={busy} />
        <button className="act primary" type="submit" disabled={busy || !q.trim()}>
          {busy ? "…" : "Ask"}
        </button>
      </form>

      <div className="chat-foot">
        <label className="toggle">
          <input type="checkbox" checked={useLLM} onChange={(e) => setUseLLM(e.target.checked)} />
          Route with a language model
        </label>
        <span className="sub">
          {useLLM
            ? "The model picks the query; if it answers off-contract, the keyword router takes over."
            : "Deterministic keyword routing - instant, and the default."}
        </span>
        {turns.length > 0 && (
          <button className="act" onClick={() => setTurns([])}>Clear</button>
        )}
      </div>
    </div>
  );
}
